orchestrator:
  pipelines:
    - name: data-gent-renew-devices
      input:
        name: Ldio:HttpInPoller
        config:
          url:
            - "https://renew.iccs.gr/projects/41837b47-5e2f-4e25-973b-ae74980b7ea8/devices/8471de9c-6446-4c7f-ae3b-1171c7bef625/observations/latest"
          interval: PT15M
        adapter:
          name: Ldio:JsonToLdAdapter  # Convert to linked data
          config:
            context: |
              {
                "@context": {
                  "@base": "https://renew.iccs.gr/projects/41837b47-5e2f-4e25-973b-ae74980b7ea8/devices/",
                  "sosa": "http://www.w3.org/ns/sosa/",
                  "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                  "xsd": "http://www.w3.org/2001/XMLSchema#",
                  "prov": "http://www.w3.org/ns/prov#",
                  "qudt": "http://qudt.org/schema/qudt/",
                  "si-unit": "https://si-digital-framework.org/SI/units/",
                  "waterkwaliteit": "https://data.vlaanderen.be/ns/waterkwaliteit#",
                  "schema": "https://schema.org/",
                  "id": "@id",
                  "type": "@type",
                  "time": {
                    "@id": "prov:generatedAtTime",
                    "@type": "xsd:dateTime"
                  },
                  "float_value": {
                    "@id": "qudt:numericValue",
                    "@type": "xsd:float"
                  },
                  "string_value": {
                    "@id": "qudt:value",
                    "@type": "xsd:string"
                  },
                  "location": {
                    "@id": "waterkwaliteit:locatie",
                    "@type": "@id"
                  },
                  "ObservedPropertyType": {
                    "@id": "sosa:observedProperty",
                    "@type": "@id"
                  },
                  "observed_property_type_name": {
                    "@id": "rdfs:label",
                    "@type": "xsd:string"
                  },
                  "unit": {
                    "@id": "qudt:siExactMatch",
                    "@type": "xsd:string"
                  },
                  "hasResult": {
                    "@id": "sosa:hasResult",
                    "@type": "@id"
                  },
                "properties": {
                    "@id": "schema:additionalProperty",
                    "@type": "@id"
                 },
                  "value_type": {
                    "@id": "qudt:hasQuantityKind",
                    "@type": "xsd:string"
                  },
                 "null_value": null
                }
              }
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: "devices-ghent.rq"  # Path to your SPARQL query file
      outputs:
        - name: Ldio:HttpOut
          config:
            endpoint: http://host.docker.internal:8089/renew-observations
            content-type: application/n-quads
        - name: Ldio:ConsoleOut
          config:
            rdf-writer:
              content-type: text/turtle  # Specify the RDF format for the output
    - name: data-zelzate-renew-devices
      input:
        name: Ldio:HttpInPoller
        config:
          url:
            - "https://renew.iccs.gr/projects/41837b47-5e2f-4e25-973b-ae74980b7ea8/devices/be61a56a-038b-44dc-86f2-8c319739efc8/observations/latest"
          interval: PT15M
        adapter:
          name: Ldio:JsonToLdAdapter  # Convert to linked data
          config:
            context: |
              {
                "@context": {
                  "@base": "https://renew.iccs.gr/projects/41837b47-5e2f-4e25-973b-ae74980b7ea8/devices/",
                  "sosa": "http://www.w3.org/ns/sosa/",
                  "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                  "xsd": "http://www.w3.org/2001/XMLSchema#",
                  "prov": "http://www.w3.org/ns/prov#",
                  "qudt": "http://qudt.org/schema/qudt/",
                  "si-unit": "https://si-digital-framework.org/SI/units/",
                  "waterkwaliteit": "https://data.vlaanderen.be/ns/waterkwaliteit#",
                  "schema": "https://schema.org/",
                  "id": "@id",
                  "type": "@type",
                  "time": {
                    "@id": "prov:generatedAtTime",
                    "@type": "xsd:dateTime"
                  },
                  "float_value": {
                    "@id": "qudt:numericValue",
                    "@type": "xsd:float"
                  },
                  "string_value": {
                    "@id": "qudt:value",
                    "@type": "xsd:string"
                  },
                  "location": {
                    "@id": "waterkwaliteit:locatie",
                    "@type": "@id"
                  },
                  "ObservedPropertyType": {
                    "@id": "sosa:observedProperty",
                    "@type": "@id"
                  },
                  "observed_property_type_name": {
                    "@id": "rdfs:label",
                    "@type": "xsd:string"
                  },
                  "unit": {
                    "@id": "qudt:siExactMatch",
                    "@type": "xsd:string"
                  },
                "properties": {
                    "@id": "schema:additionalProperty",
                    "@type": "@id"
                 },
                  "value_type": {
                    "@id": "qudt:hasQuantityKind",
                    "@type": "xsd:string"
                  },
                 "null_value": null
                }
              }
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: "devices-zelzate.rq"  # Path to your SPARQL query file
      outputs:
        - name: Ldio:HttpOut
          config:
             endpoint: http://host.docker.internal:8089/renew-observations
             content-type: application/n-quads
        - name: Ldio:ConsoleOut
          config:
              rdf-writer:
              content-type: text/turtle
